#!/usr/bin/env node
/**
 * Build one unpacked extension for each browser.
 *
 * Chrome and Firefox need different manifests: a service worker against an
 * event page, declarativeNetRequest against webRequest. The rest of the code
 * is the same, so it is copied.
 */

import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
	DEV_WIKI_MATCHES, PROD_WIKI_MATCHES, NON_WIKI_MATCHES, GERRIT_ORIGIN
} from './shared/constants.js';

const ROOT = dirname( fileURLToPath( import.meta.url ) );
const DIST = join( ROOT, 'dist' );
const VERSION = '0.1.0';

const SOURCE_DIRS = [ 'background', 'content', 'shared', 'popup', 'options', 'icons', 'vendor' ];

const WIKI_MATCHES = [ ...DEV_WIKI_MATCHES, ...PROD_WIKI_MATCHES ];

function baseManifest() {
	return {
		manifest_version: 3,
		name: 'WikimediaPatched',
		version: VERSION,
		description:
			'Apply unmerged Gerrit patches to live Wikimedia wikis. Client-side code only.',
		permissions: [ 'storage', 'cookies', 'scripting', 'tabs', 'webNavigation' ],
		host_permissions: [ GERRIT_ORIGIN + '/*', ...DEV_WIKI_MATCHES ],
		optional_host_permissions: PROD_WIKI_MATCHES,
		icons: {
			16: 'icons/icon-16.png',
			32: 'icons/icon-32.png',
			48: 'icons/icon-48.png',
			128: 'icons/icon-128.png'
		},
		action: {
			default_popup: 'popup/popup.html',
			default_title: 'WikimediaPatched',
			default_icon: {
				16: 'icons/icon-16.png',
				32: 'icons/icon-32.png'
			}
		},
		options_ui: { page: 'options/options.html', open_in_tab: true },
		content_scripts: [
			{
				matches: WIKI_MATCHES,
				exclude_matches: NON_WIKI_MATCHES,
				js: [ 'content/main-world.js' ],
				run_at: 'document_start',
				world: 'MAIN',
				all_frames: false
			},
			{
				matches: WIKI_MATCHES,
				exclude_matches: NON_WIKI_MATCHES,
				js: [ 'content/bridge.js' ],
				run_at: 'document_start',
				all_frames: false
			}
		],
		web_accessible_resources: [
			{ resources: [ 'content/main-world.js' ], matches: WIKI_MATCHES }
		]
	};
}

function chromeManifest() {
	const m = baseManifest();
	m.background = { service_worker: 'background/sw.js', type: 'module' };
	// Phase 4 rewrites the startup module URL instead of setting a cookie.
	m.permissions.push( 'declarativeNetRequest' );
	return m;
}

function firefoxManifest() {
	const m = baseManifest();
	// Firefox keeps event pages, which survive better than a service worker.
	m.background = { scripts: [ 'background/sw.js' ], type: 'module' };
	m.permissions.push( 'webRequest', 'webRequestBlocking' );
	m.browser_specific_settings = {
		gecko: { id: 'wikimedia-patched@wikimedia.org', strict_min_version: '128.0' }
	};
	return m;
}

/**
 * Inline the files a content script asks for.
 *
 * A content script cannot be an ES module, but the pure helpers must stay
 * importable so the unit tests can reach them. So the build pastes them in
 * and drops the `export` keyword.
 *
 * @param {string} source
 * @return {Promise<string>}
 */
async function inlineIncludes( source ) {
	const lines = source.split( '\n' );
	const out = [];
	for ( const line of lines ) {
		const m = /^(\s*)\/\/ @include (\S+)$/.exec( line );
		if ( !m ) {
			out.push( line );
			continue;
		}
		const text = await readFile( join( ROOT, m[ 2 ] ), 'utf8' );
		out.push( `${ m[ 1 ] }// --- inlined from ${ m[ 2 ] } ---` );
		out.push( text.replace( /^export (const|function|class|let|var) /gm, '$1 ' ) );
		out.push( `${ m[ 1 ] }// --- end ${ m[ 2 ] } ---` );
	}
	return out.join( '\n' );
}

/**
 * Put the LESS compiler into vendor/, from node_modules.
 *
 * less ships a UMD browser build. Giving it a `module` object makes it
 * behave as CommonJS, and the wrapper then exports it as an ES module so a
 * background worker can import it.
 *
 * Without node_modules/less the placeholder stays, and the extension says
 * so instead of failing quietly.
 */
async function vendorLess() {
	const candidates = [
		'node_modules/less/dist/less.min.js',
		'node_modules/less/dist/less.js'
	];
	for ( const rel of candidates ) {
		let umd;
		try {
			umd = await readFile( join( ROOT, rel ), 'utf8' );
		} catch ( e ) {
			continue;
		}
		const wrapped = [
			`// Generated by build.mjs from ${ rel }. Do not edit.`,
			'const module = { exports: {} };',
			'const exports = module.exports;',
			'const window = globalThis;',
			umd,
			'export default module.exports.default || module.exports || globalThis.less;',
			''
		].join( '\n' );
		await writeFile( join( ROOT, 'vendor', 'less.js' ), wrapped );
		console.log( `vendored ${ rel }` );
		return true;
	}
	console.log( 'no node_modules/less; stylesheets that need a compiler will be skipped' );
	return false;
}

async function buildOne( name, manifest ) {
	const out = join( DIST, name );
	await rm( out, { recursive: true, force: true } );
	await mkdir( out, { recursive: true } );
	for ( const dir of SOURCE_DIRS ) {
		await cp( join( ROOT, dir ), join( out, dir ), { recursive: true } ).catch( () => {} );
	}
	// Content scripts cannot import, so their includes are pasted in.
	for ( const file of [ 'content/main-world.js', 'content/bridge.js' ] ) {
		const src = await readFile( join( ROOT, file ), 'utf8' );
		await writeFile( join( out, file ), await inlineIncludes( src ) );
	}
	await writeFile(
		join( out, 'manifest.json' ), JSON.stringify( manifest, null, '\t' ) + '\n'
	);
	console.log( `built dist/${ name }` );
}

await vendorLess();
await buildOne( 'chrome', chromeManifest() );
await buildOne( 'firefox', firefoxManifest() );
